language: node_js
node_js:
    - "7"
    - "6"
script:
  - npm run coverage
notifications:
  slack:
    secure: dePfiEtg6FU//zFLSGJ42pkead4n2bpS74w6zx8PKH4Brhki+biIbDfECkfH5zRdggry2ETnxSzQfZyk5+OVOq+H/vPXABC8sHaO8xR97TqD9WQcQO0R14cu8AcDV8Nrg6zi8K1PgqIfJPt7vW98yZjgqMuDRJYuwiREo+XKyfGZj/pNrmVzOo2L+uSr4bSnl8G7syYPwNQ3sqqru2f3pBJM5wBE1Xd9GK146Ldz3fc1guc7R78i3/lz5jQHjXuXUGrvBaFTdEDVyPCOZj+sbX8qlKKF587qWMHW3La52tEEO9Bqu21Pt8VbW1S0J5tMGuRuIV648p3bOnzbOtOAs/bEbwRGGgZEhpoLBEigC5nAgBmNLnheTpuirSpC6yO+SDYS4rGikrAGTjSOKEaLHX1WOYrlL0PR5MGInSN7lHQkiKLTsD+P6NtIghieQTxcF+znpC0lYfq435dlGnr0hsqOTHDlTS8XtLGXucTSyd8q8bPBW33sXppyRS7iBmQQPbW3NXylAGZw6Itz0mDnXF728ce7dYd2SZNCpp4WLtiUYShIpinNELO+0cRy+kUpalbElJEdL4zAGQayOplSWStbHZxV6nFZ4BfqSfo+gT9J5feI9NYnMLWs4bsSz7rjERQ4ggHnzhJjfmSaApzYmea1copREFaZDNVB39XBji0=
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
